apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    name: mongodb
    tier: db
  ports:
    - port: 27017
      name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
      tier: db
  serviceName: "mongodb"
  template:
    metadata:
      labels:
        name: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: revanthsatyam/mongodb:k8
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 1Gi