apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    name: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      tier: db
  serviceName: "redis"
  template:
    metadata:
      labels:
        name: redis
        tier: db
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 1Gi